const { DataTypes } = require('sequelize');
const sequelize = require('./db');

const CDR = sequelize.define('CDR', {
  id: {
    type: DataTypes.STRING,
    primaryKey: true,
    defaultValue: () => `cdr_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
  },
  callere164: DataTypes.STRING,
  calleraccesse164: DataTypes.STRING,
  calleee164: DataTypes.STRING,
  calleeaccesse164: DataTypes.STRING,
  callerip: DataTypes.STRING,
  callerrtpip: DataTypes.STRING,
  callercodec: DataTypes.STRING,
  callergatewayid: DataTypes.STRING,
  callerproductid: DataTypes.STRING,
  callertogatewaye164: DataTypes.STRING,
  callertype: DataTypes.STRING,
  calleeip: DataTypes.STRING,
  calleertpip: DataTypes.STRING,
  calleecodec: DataTypes.STRING,
  calleegatewayid: DataTypes.STRING,
  calleeproductid: DataTypes.STRING,
  calleetogatewaye164: DataTypes.STRING,
  calleetype: DataTypes.STRING,
  billingmode: DataTypes.STRING,
  calllevel: DataTypes.STRING,
  agentfeetime: DataTypes.STRING,
  starttime: DataTypes.DATE,
  stoptime: DataTypes.DATE,
  callerpdd: DataTypes.INTEGER,
  calleepdd: DataTypes.INTEGER,
  holdtime: DataTypes.INTEGER,
  duration: DataTypes.INTEGER,
  callerareacode: DataTypes.STRING,
  feetime: DataTypes.INTEGER,
  fee: DataTypes.DECIMAL(10, 4),
  tax: DataTypes.DECIMAL(10, 4),
  suitefee: DataTypes.DECIMAL(10, 4),
  suitefeetime: DataTypes.INTEGER,
  incomefee: DataTypes.DECIMAL(10, 4),
  incometax: DataTypes.DECIMAL(10, 4),
  customeraccount: DataTypes.STRING,
  customername: DataTypes.STRING,
  customer_id: DataTypes.STRING,
  calleeareacode: DataTypes.STRING,
  agentfee: DataTypes.DECIMAL(10, 4),
  agenttax: DataTypes.DECIMAL(10, 4),
  agentsuitefee: DataTypes.DECIMAL(10, 4),
  agentsuitefeetime: DataTypes.INTEGER,
  agentaccount: DataTypes.STRING,
  agentname: DataTypes.STRING,
  flowno: DataTypes.STRING,
  softswitchname: DataTypes.STRING,
  softswitchcallid: DataTypes.STRING,
  callercallid: DataTypes.STRING,
  calleroriginalcallid: DataTypes.STRING,
  calleecallid: DataTypes.STRING,
  calleroriginalinfo: DataTypes.STRING,
  rtpforward: DataTypes.STRING,
  enddirection: DataTypes.STRING,
  endreason: DataTypes.STRING,
  status: DataTypes.STRING,
  call_type: DataTypes.STRING,
  billingtype: DataTypes.STRING,
  cdrlevel: DataTypes.STRING,
  agentcdr_id: DataTypes.STRING,
  sipreasonheader: DataTypes.STRING,
  recordstarttime: DataTypes.DATE,
  transactionid: DataTypes.STRING,
  flownofirst: DataTypes.STRING
}, {
  tableName: 'cdrs',
  timestamps: true
});

module.exports = CDR;
